### ISSUE TITLE
Implement std::error::Error for NFDError

### ISSUE THREAD

**Issue by Shadlock0133** [EmbarkStudios/nfd2#7]
`NFDError` is missing `Error` implementation. It should be easy to either write it manually or use e.g. `thiserror` to derive it.

**Comment by Jake-Shadle** [comment]
Oops! We should definitely have that.

**Comment by sunjay** [comment]
Since you already implement `Debug` and `Display` for `NFDError`, adding an impl is as easy as just writing `impl Error for NFDError {}`. I opened a PR (#9) to do that. I don't think it is worth it to add `thiserror` given its impact on compile time and that you would only save on a tiny bit of boilerplate. Please take a look at my PR when you have a chance. :)
